spatie/package-skeleton-laravel

src/SkeletonClass.php
src/SkeletonServiceProvider.php

This will fix StyleCI for the skeleton repo

StyleCI fixes

---

composer.json

There is a space you probably don't want there 😊 This PR removes that space.

Remove space

---

.gitattributes

I'll submit this here as well, to make sure this trickles down to all yet-to-be-created packages. 🙂

Don't export .editorconfig file

---

composer.json

This will make any package you develop using this template work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5

Add AutoDiscovery to next Spatie Packages

---

composer.json

This PR removes a blank line in the `composer.json` file.

Removes blank line.

---

database/migrations/create_skeleton_table.php.stub
src/SkeletonServiceProvider.php
tests/TestCase.php

I believe this was a type, It makes more sense have it as `table` rather than `tables` :).

Fixing a possible typo

---

configure-skeleton.sh

as requested :-)
I included some basic bash functions from [pforret/bash-boilerplate](https://github.com/pforret/bash-boilerplate) to improve readability

clean up code - don't change itself - pass shellcheck

---

configure-skeleton.sh

I've updated the shell script to automatically replace the placeholder values such as "skeleton", "spatie". I've used the generated suggested ClassName ( which was already there ) for replacing `Skeleton` class name. and added a user input to get the vendor name and replaced it with "spatie". moreover, I 've renamed the files according to the package name. Hope this will save some time.

Updated the shell script to replace the placeholder values such as "skeleton","spatie"

---

configure-skeleton.sh

Same as https://github.com/spatie/package-skeleton-php/pull/15

Change order of questions

---

configure-skeleton.sh

Ask for class name too, by default suggested class name.
It is because sometimes the package is called "laravel-simple-calculator" and the suggested class name is "LaravelSimpleCalculator" and you want it is just be "SimpleCalculator", and is a mess change all file's name, composer.json, sometimes you miss something, blabla. So, it ask if the suggested class name is ok or optional you can change it.  
Thanks for all your amazing work!

Ask for Class Name too.

---

.github/workflows/run-tests.yml

See https://getcomposer.org/upgrade/UPGRADE-2.0.md:
`Deprecated --no-suggest flag as it is not needed anymore`

Remove deprecated `no-suggest` option

---

.github/workflows/run-tests.yml

`stability` is probably a better key name to use here instead of `dependency-version`.

dependency-version -> stability

---

.github/workflows/run-tests.yml

- Fixes typo: matches -> matche**r**s
- Made the name lowercase just like other step names.

Fixes typo

---

README.md

The test name in the bage was wrong.

Fix test name in badge

---

.github/ISSUE_TEMPLATE/config.yml

This makes the language used for Ask a Question consistent with the other two options.

Rename Ask a Question to Question

---

.github/FUNDING.yml
.github/SECURITY.md
LICENSE.md
composer.json
configure-skeleton.sh

Porting changes from https://github.com/spatie/package-skeleton-php/pull/33 as requested

Replace leftover Spatie references during configure-skeleton

---

README.md

I think this badge can be useful in some cases

ADD code style badge in readme

---

configure-skeleton.sh

Added a camel case vendor variable and used that to swap out Spatie

Added a pascal case variant of the vendor name variable

---

database/migrations/create_skeleton_table.php.stub

fix(migration): fixed a small missing semicolon

---

.php_cs.dist.php

https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5669
https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/a04d9c50ad8b00ac489001cf691b0183f985a8c9

Rename Trailing Comma In Multiline Array

---

.github/ISSUE_TEMPLATE/config.yml
README.md
composer.json

Hi spatie team
First of all thx for this great package 👏 
I found a little 'bug' , the vendor_slug and package_slug are not replaced.  This pull request fixes that issue
Kind regards 
Dieter

fix vendor_slug and package_slug

---

configure.php

Hi spatie team
First of all thank you for this great package 👏
This package does not work on windows due to missing grep. This pull adresses that using windows available commands.
Kind regards
Carlos

Adding windows support

---

configure.php

This PR makes using `phpstan/larastan`, `php-cs-fixer`, and the `auto changelog` workflow features optional when running the `configure.php` script.  
This allows developers more flexibility when using this skeleton as a template for their own packages, increasing the overall number of users who may use in addition to an increase in developer satisfaction.
Selecting "no" for phpstan causes the following packages & scripts to be removed from `composer.json`:
- `phpstan/extension-installer`
- `phpstan/phpstan-deprecation-rules`
- `phpstan/phpstan-phpunit`
- `nunomaduro/larastan`
- `phpstan` _(script)_
As well as the following files:
- `phpstan.neon.dist`
- `phpstan-baseline.neon`
- `.github/workflows/phpstan.yml`
Selecting "no" for `php-cs-fixer` causes the following files to be removed:
- …

Feature: Make some package features optional

---

.github/workflows/run-tests.yml
composer.json

This PR contains minor package maintenance; specifically, it bumps `composer.json` and `run-tests.yml` dependency versions to their latest.

Minor Package Maintenance 

---

README.md
configure.php

Automatic remove paragraphs inside of README.md when they are inside of ``
Better readability for `fix renaming files in Windows #166`

Remove README paragraphs(instructions)

---

README.md

Since it looks like you're following this pattern, I submit this PR just so the code stays homogeneous.

MD031 Fenced code blocks should be surrounded by blank lines

---

README.md

The `configure.php` script will delete the block of text automatically.

Remove "Remove this block of text" step

---

.github/CONTRIBUTING.md

Updated to PSR-12 Coding Standard

---

composer.json

Set minimum PHP version

---

README.md

Currently the code style badge is not referencing the correct action name. This PR corrects that.

Update readme to fix code style badge to reference correct action name.

---

composer.json

https://packages.tools/testbench/getting-started/introduction.html#installation

Follow Testbench recommended installation guide

---

.editorconfig

https://github.com/laravel/laravel/pull/6012

Sort EditorConfig rules

---

.github/workflows/run-tests.yml
composer.json

This updates the dependencies for Laravel 10 and the tests workflow to match.

bump default versions to Laravel 10

---

.gitignore

See https://github.com/laravel/laravel/pull/6052/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R1

Ignore PHPUnit 10 cache

---

.gitattributes
composer.json
workbench/app/Providers/WorkbenchServiceProvider.php

New experimental features available with Testbench 7.28 and 8.8: https://github.com/orchestral/workbench

Support Workbench

---

composer.json

Fix composer.json syntax to fix composer install execution

Fix composer.json syntax

---

composer.json

Please see [https://x.com/enunomaduro/status/1731969850048676065](https://x.com/enunomaduro/status/1731969850048676065)

update nunomaduro/larastan to larastan/larastan

---

composer.json

Makes the package work with the newest Laravel version

Compatibility for Laravel 12
