spatie/package-skeleton-laravel

composer.json
Fixes the `test-coverage` script to use vendor installed `phpunit` rather than from the host system.
=> Update test-coverage script phpunit path

CONTRIBUTING.md
Let's make the web a little bit more secure 😄
The [link in .editorconfig](https://github.com/spatie/skeleton-php/blob/9ff308cde326f18f1bd29e28dd6f6a29faa850b2/.editorconfig#L2) is still http because the [editorconfig site](https://editorconfig.org) doesn't support https 😢
=> Update links to https

composer.json
As you can [see](https://github.com/larapack/dd/blob/master/src/helper.php#L3), **larapack/dd** just adds a helper function, but in the latest versions of **symfony/var-dumper** it already is, so we don't need this package
=> Replacement of unnecessary package

.php_cs
Quick fix for what I believe is an accidental duplicate statement in the `.php_cs` file to exclude the `storage/*` path. 👯‍♂️
=> Removing duplicate statement in php_cs.

configure-skeleton.sh
The \s doesn't work for some implementations of sed.
On mac, using \s removes 's' from the class name and keep spaces.
Changing to the POSIX compliant value [[:space:]] fixes it for all.
Fixes #32 , tested on mac (had issue) and ubuntu (didn't have issue)
=> Changing to POSIX compliant sed expression

configure-skeleton.sh
This should fix the migration rename problem mentioned in #36
=> configure-skeleton changes migration class name but not file name

configure-skeleton.sh
The configure script searches in files to replace relevant values.
It will also scan the `vendor` folder in case you did `composer install` before running the configure script.
I have excluded the `vendor` folder to prevent making changes in the `vendor` folder.
=> Exclude `vendor` dir

README.md
Updated the `composer require` command in the `README` to use the `:package_name` placeholder.
=> Use :package_name placeholder

tests/TestCase.php
See #66 
I have kept the `setupUp` method in place for convenience.
=> Remove call to `withFactories` method

composer.json, database/factories/ModelFactory.php, tests/TestCase.php
I have added the `guessFactoryNamesUsing` in the `setUp` method.
Laravel doesn't know where to find the `Factory` classes and it will assume the default `Database\Factories` namespace.
Note that there is also a `useNamespace` method to set the namespace, but found out this doesn't work here.
Think this could be improved in the framework itself.
Resolves #66
=> Laravel 8 model factories

composer.json
I would suggest adding `illuminate/contracts`:`^8.0` as a minimum requirement.
=> Add `illuminate/contracts`

configure-skeleton.sh
Hey there !
I noticed a typo in the word _**unsanitized**_ ( written **_unsantized_**) in the `configure-skeleton.sh` script.
Also, any chance in seeing the equivalent script added on the [skeleton-nova-tool](https://github.com/spatie/skeleton-nova-tool) repo ?
Cheers from Eigenbrakel !
=> Correct typo in configure-skeleton.sh

composer.json
Composer scripts includes psalm and a config file is included, but psalm is not included in the dev dependencies.
=> Include psalm dev dependancy

.github/workflows/run-tests.yml
The name of the test flow used in Github Actions must match the name provided in the badge for tests:
```
// README.md
[![GitHub Tests Action Status](https://img.shields.io/github/workflow/status/:vendor_name/:package_name/run-tests?label=tests)](https://github.com/:vendor_name/:package_name/actions?query=workflow%3ATests+branch%3Amaster)
```
Note that it says `run-tests?...` and this should match the name of the flow specified in `.github/workflows/run-tests.yml` for this image to work.
=> Bugfix: Match Github flow name with Github test badge

.gitattributes, .gitignore, composer.json, testbench.yaml
This will auto-register the package service provider when running CLI Commander via Testbench, see <https://packages.tools/testbench/commander.html>
For example, based on Freek live coding https://www.youtube.com/watch?v=3HPTh-EMY2U, you test the `remote` command directly from Testbench (without having a dummy Laravel app).
```
./vendor/bin/testbench remote "whoami"
```
=> Add testbench.yaml by default

composer.json
The issue is explained here: https://github.com/spatie/laravel-package-tools/issues/20
=> Fix test failing when using --prefer-lowest. Using missing methods

README.md, configure-skeleton.sh
I did this little change to make the configuration compliant with the latest `laravel-package-tools` releases, which use the package's short name in the commands used to publish migration and config files.
=> Add short_package_name variable

.github/workflows/psalm.yml
This will prevent this issue
```php
- Root composer.json requires php ^8.0 but your php version (7.4.16) does not satisfy that requirement.
```
=> Update psalm.yml PHP version

README.md
The "tests" badge link in the README was pointing to a workflow named `Tests` and returning no results. It seems the correct workflow name is `run-tests`.
=> Fix tests badge link

.github/workflows/run-tests.yml
Currently the `prefer-lowest` test always fails due to Testbench calling a `getAnnotations()` method that PHPUnit 9.5 no longer provides. See #116 for an example of this failure.
Testbench 6.6.0 fixed this, however `prefer-lowest` currently pulls in 6.0.0.
This PR increases the minimum version tested to `6.6`.
=> Fix "prefer-lowest" test from always failing

.github/workflows/run-tests.yml
When creating a PR from a branch within the same repo (i.e. not a fork), the current run-test workflows get triggered twice - for both `push` and `pull_request`:
(Note this does not happen when others push to their own fork as discovered in my experiment at #118)
This PR makes it so that only pushes and pull requests directly to `master` will trigger a workflow run, which fixes the double-up:
(Side note: I think it would be good to change the default branch to `main` per https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name)
=> Prevent workflow running twice when PRing a branch from the same repo

.github/workflows/run-tests.yml, README.md
This PR fixes the Github workflow and badges in the README.md that refer to the default branch.
Since it was changed from `master` to `main` from https://github.com/spatie/package-skeleton-laravel/issues/125.
=> fix: change branch references from `master` to `main`

configure-skeleton.sh
Replace vendor_name, vendor_slug and author@domain.com within the `.github` directory automatically
=> Replace variables within .github directory

configure-skeleton.sh
Somewhere in one of the files that are being run through `sed` is a forward slash. This causes `sed` to throw errors (`sed: 1: "s/:package_description/ ...": bad flag in substitute command: 'f'`) because it thinks the token is complete before it really is. Changing the delimiters to something else fixes this problem.
I have tested this on macOS 11.4, Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
=> Fix configure errors on macOS

configure-skeleton.sh
This pull request adds a new "Vendor namespace" question to the configuration script, allowing you to customise the vendor namespace.
This is useful for scenarios where the vendor name for the package differs, e.g. I use `ryangjchandler` for the vendor name but `RyanChandler` for the namespace.
=> feature: allow customising namespace in configure script

config/skeleton.php
The placeholder `ClassName` in config/skeleton.php is not replaced when running `./configure-skeleton.sh`
This pull request changes the placeholder to use `Skeleton` instead.
**Current behavior**
```
<?php
// config for Vurpa/ClassName
return [
];
```
**With this pull request**
```
<?php
// config for Vurpa/PackageSkeletonLaravel
return [
];
```
=> Placeholder "ClassName" in config/skeleton.php is not replaced

configure.php
There are some missing parts on configuration.php file. I think it's related to #146, the PHP configuration script added instead of the bash script does not do some of the things that the bash script does.
The problems that I encounter:
- does not rename migration file
- does not rename config file
- does not change `skeleton` in all files, (it only changes `Skeleton` but code includes both `Skeleton` and `skeleton`)
I think I fixed all of them but I was using this package first time. So I'm not sure whether the missing parts and all use cases are covered. It would be great if you could check it out, thanks!
=> Fix missing parts in configuration script

tests/TestCase.php
If the setUp() signature is public instead of protected an error will be thrown by Pest:
`Access level to Pest\Concerns\Testable::setUp() must be public (as in class VendorName\Skeleton\Tests\TestCase)
`
and tests will not run.   This fixes the issue, bringing it in line with the Orchestra TestBench documentation.
=> Fix setUp() signature to match with Pest

composer.json
It looks like the colons were removed from the composer.json file yesterday.
=> Add template colons into name

configure.php
It looks like that the folders structures had been updated but the `configure.php` still trying to rename the old facade class.
It was on `src/SkeletonFacade.php` and the current structure is `src/Facades/Skeleton.php`
=> fixed renaming 'src/Facades/Skeleton.php' in configure.php

.github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
This PR adds a GitHub Dependabot config file & workflow for updating github action versions. It auto-merges the PRs for minor and patch versions only, and only creates PRs for major version updates. It checks for updates once weekly.
I feel this is a necessary and important step forward in maintaining a large number of packages as I've discovered a number of outdated GitHub action versions that should have been updated long ago while working on PHP 8.1 updates. There is no reason, in my opinion, not to automate the updating of github action versions.
This PR was created in relation to [spatie/package-skeleton-php #54](https://github.com/spatie/package-skeleton-php/pull/54).
=> Dependabot Updates for Github Actions

configure.php
The `replaceForWindows` function results a weird behavior. 
With the old function, the files in `.github` like `FUNDING.yml` didn't get affected by the script `configure.php` 
Also, for some reason the script included the file `.git/index`,  which resulted in the following behavior.
``` 
fkous@7rouz MINGW64 /d/testing (main)
$ ./configure.php
Author name (koossaayy):
Author email (tounessna.2010@gmail.com):
Author username (koossaayy):
Vendor name (koossaayy):
Vendor namespace (Koossaayy):
Package name (testing):
Class name (Testing):
Package description (This is my package testing):
Enable PhpStan? (Y/n):
Enable PhpCsFixer? (Y/n):
Use automatic changelog updater workflow? (Y/n):
------
Author     : koossaayy (koossaayy, *********@gmail.com)
Vendor     : koossaayy (koossaayy)
Package    : …
```
=> Fix the 'replaceForWindows' function

configure.php
This PR will fix the renaming feature in Windows systems. 
Windows is using this convention in file paths : `D:\testing\file.php` while others are using `var/www/htdocs/file.php` 
So by fixing the feature, files now will be renamed when executing the configure script.
=> fix renaming files in Windows

README.md, configure.php
The generated boilerplate code in the README contains a variable that will be filled with an illegal character (-) if the package contains multiple words (e.g. test-package). This change turns 
```php
$example-package = new VendorName\ExamplePackage();
echo $example-package->echoPhrase('Hello, VendorName!');
```
into
```php
$examplePackage = new VendorName\ExamplePackage();
echo $examplePackage->echoPhrase('Hello, VendorName!');
```
=> Prevent dashes (-) from appearing in PHP variable names

README.md
Place it directly after publishing config command documentation
=> Move contents of config example

composer.json
When running the `composer run test-coverage` script prior to this change it would result in an error. This is due to pest/phpunit attempting to run a file called `coverage`. `coverage` is actually a flag as [documented here](https://pestphp.com/docs/coverage).
Error before:
After:
=> Composer scripts fix: `coverage` is a flag

configure.php, database/migrations/create_skeleton_table.php.stub
According to [SQL naming conventions](https://www.sqlshack.com/learn-sql-naming-conventions), we need to generalize the name of the skeleton table
Sometimes, the developer (package author) wants to create a package with two separate words (e.g. laravel-backup)
Once the script (`configure.php`) starts replacing the placeholders, it replaces the table name like this `laravel-backup_table`
This PR converts the hyphen (-) on the skeleton table name to underscore `_` symbol, and the table will be always `laravel_backup_table`
=> generalize skeleton table name convention

composer.json
I was not able to run composer install after running configure.php script because of the typo in the template.
=> fix collision version string

composer.json
Since the package skeleton is updated to require a minimum of laravel 9 already, might as well bump larastan too.
=> Bump Larastan to next major version.

configure.php
This suppresses the following deprecation notice:
```
➜  package-skeleton-laravel git:(main) php ./configure.php
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/rick/Code/dc/src/github-forks/package-skeleton-laravel/configure.php on line 29
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/rick/Code/dc/src/github-forks/package-skeleton-laravel/configure.php on line 29
Author name:
```
=> Suppress PHP 8.1 trim() deprecation notice.

.github/workflows/phpstan.yml
Using 8.0 fails in GitHub actions workflow
=> Updated PHP version from 8.0 to 8.1 on PHPStan

configure.php
This PR adds support for removing dependabot support from the repository when running the `configure.php` script.  If disabled, it removes `.github/dependabot.yml` and `.github/workflow/dependabot-auto-merge.yml`.
The default value when prompted is to leave the feature enabled.
While dependabot should be used in most cases IMO, to add flexibility to this template repository I felt that making it an optional feature made sense.
=> Add optional dependabot support in configure script

configure.php
This PR updates the `configure.php` script to make the `spatie/laravel-ray` package optional, and it defaults to enabled.
While many Laravel packages should use Ray in my opinion, not all developers have Ray and/or want to use it for every package.  This update allows for a streamlined experience by allowing developers to easily remove the `spatie/laravel-ray` package if they don't want or need it.
This PR improves the overall developer experience by allowing for additional initial customization of the package via the easy-to-use configuration script.
=> Make spatie/laravel-ray package optional

src/Facades/Skeleton.php
The getFacadeAccessor method must always return a container binding key. In previous releases of Laravel, this method could return an object instance; however, this behavior is no longer supported.
=> in Facade creation return a container binding key

pint.json
This PR adds the pint configuration file for excluding the `build` folder that contains `phpstan` generated cache files.
=> Exclude build folder

README.md
I guess that the generated link only works on users' profiles, not enterprise profiles.
As you can see here [https://github.com/elaborate-code/.github/blob/main/CONTRIBUTING.md](https://github.com/elaborate-code/.github/blob/main/CONTRIBUTING.md) it gives 404 while file exists normally [https://github.com/elaborate-code/laravel-resource-routes/blob/main/CONTRIBUTING.md](https://github.com/elaborate-code/laravel-resource-routes/blob/main/CONTRIBUTING.md)
=> path to CONTRIBUTING.md

.github/workflows/fix-php-code-style-issues.yml
There were no changes in the action. The maintainer decided to create a new tag and release `v1.0.0`. But Dependabot will be notifying about the upgrade and creating a PR
=> Upgrade laravel-pint-action v0.1.0 to v1.0.0

.github/workflows/run-tests.yml
It makes it easier to debug if the build is configured correctly. 
Composer for Windows for example doesn't work nicely when you use `^9.0` instead of `9.x`
=> Show list of installed dependencies

composer.json
I have used this template several times and stumbled upon the following [issue](https://github.com/elaborate-code/laravel-json-localization/actions/runs/3192843837/jobs/5210776100#step:5:254) a couple of times on the testing workflow and every time I fix it by the change I'm proposing here.
=> allow composer plugins for test

.github/workflows/run-tests.yml
This pull request aims to fix run-tests workflow which is throwing errors when running on PHP 8.2 and installing dependencies at their lowest version.
A similar fix has been made in laravel/framework: https://github.com/laravel/framework/pull/44374/files
The alternative would then be requiring a minor version of the Laravel framework, but it would probably be too restrictive just for the version of the Carbon dependency
=> FIX run-tests workflow failing on prefer-lowest runs

composer.json
This small commit aims to update the laravel-package-tools dependency version.
In the previous version tests were failing after installing dependencies with the `prefer-lowest` option, as in version 1.13.0 the `askToRunMigrations` method was missing
=> UPDATE laravel-package-tools dependency version

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml
Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
Announcement: https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
Example of it in use:
[Feature Flags for Laravel new Issue Page](https://github.com/ylsideas/feature-flags/issues/new/choose)
[Feature Flags for Laravel Bug Report Form](https://github.com/ylsideas/feature-flags/issues/new?assignees=peterfox&labels=bug&template=bug.yml&title=%5BBug%5D%3A+)
---
I've been using this technique for a few months, and it's a lot better in guiding users of a package to provide the correct information. The form will ask for info like what happened, how to reproduce the bug, the package version, PHP version, Laravel version and …
=> [Feature] Bug reporting via GH forms

.github/workflows/fix-php-code-style-issues.yml, .github/workflows/update-changelog.yml
Update permission of default GITHUB_TOKEN to `contents: write`.
GitHub changed the default permission of the GITHUB_TOKEN to read-only at the beginning of February 2023 on all **new** repositories.[^1]
[^1]: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
=> Update permissions in GitHub Actions workflow to allow pushing changed files to repository

phpunit.xml.dist
Updates the phpunit.xml.dist for PHPUnit 10/Pest 2 and removes the warning:
```shell
WARN  Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```
=> Update phpunit.xml.dist for PHPUnit 10

composer.json
Current required version 7.9 does not exist. Use latest availabele version 7.8 instead.
=> Fix nunomaduro/collision version.

composer.json
 In JsonFile.php line 347:
                                                                                
   "./composer.json" does not contain valid JSON                                
   Parse error on line 58:                                                      
   ...nch serve",        ],        "analyse"                                    
   ---------------------^                                                       
   Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - It  
    appears you have an extra trailing comma                                    
 
=> Removed trailing comma

composer.json
Hi
Composer's scripts has a default process timeout of 300, which is obviously not convenient for launching long-running commands.
This PR disables the Composer's process timeout when using the `start` script which starts a PHP server.
=> Prevent start script timeout

configure.php
This PR enhances the configuration script by increasing the accuracy of the current user's GitHub username guess, as well as more accurately guessing the correct name and GitHub username of the vendor.
It adds several attempts at guessing the user's GitHub username, in the following order:
- it searches the commit history for the author's name _(if the project was created using this repository as a template, there will be a commit created by GitHub)_
- it attempts to use the GitHub CLI utility to determine the username
- finally, it falls back to using the username in the git remote url
It also adds guessing of the vendor name and username, by:
- using the username in the git remote url as the vendor name, then calling the GitHub API `/orgs/{username}` to retrieve the correct vendor name …
=> Enhance Author/Vendor Github username guessing

configure.php
Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization.  The configure script should adhere to change #312
=> Update configure.php to use Larastan Org

composer.json
The `arch` function was added with version 2.5.0. @freekmurze 
https://github.com/spatie/package-skeleton-laravel/blob/main/tests/ArchTest.php#L3
https://github.com/pestphp/pest-plugin-arch/commit/28519b747e94e25567ece908d580d170a9b1d9d8
```bash
Run vendor/bin/pest --ci
ERROR  Call to undefined function arch()
Location: /home/runner/work/laravel-stock/laravel-stock/tests/ArchTest.php:3
#0 /home/runner/work/laravel-stock/laravel-stock/vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(89): include_once()
#1 /home/runner/work/laravel-stock/laravel-stock/vendor/pestphp/pest/overrides/Runner/TestSuiteLoader.php(92): PHPUnit\Runner\TestSuiteLoader::PHPUnit\Runner\{closure}()
#2 /home/runner/work/laravel-stock/laravel-stock/vendor/phpunit/phpunit/src/Framework/TestSuite.php(244): …
```
=> Fixed minimum package version

composer.json
Laravel v11 Support, PHP 8.2, and other packages bump
=> Laravel v11 Support

composer.json
This PR will fix the conflict version with the `orchestra/testbench` and `nunomaduro/collision` package in laravel v11, and also support back laravel 10.
=> Resolve version conflict with some of the package and support back laravel 10

src/Facades/Skeleton.php
Title: Add return type declaration to the getFacadeAccessor method of the Skeleton class
Description:
In this PR, I added a return type declaration to the `getFacadeAccessor` method. This change can improve our code quality because:
1. It makes the code clearer and easier to read. By explicitly specifying the return type in the method signature, other developers can more easily understand the expected behavior of this method.
2. It can help us avoid type errors at runtime. If we try to return the wrong type, PHP will throw an error at compile time, not at runtime.
I look forward to your feedback!
=> Add return type declaration to function

.github/workflows/run-tests.yml
The `composer.json` file requires PHP 8.2 but the `run-tests` workflow was still including PHP 8.1.
This pull request removes it from the matrix so that tests don't fail.
=> Workflows: Remove PHP 8.1

.github/workflows/run-tests.yml
This solves an issue related to the note in this section of composer docs: 
https://getcomposer.org/doc/articles/versions.md#caret-version-range-
Compare the failed Windows job with the successful Ubuntu job here (a package created with this skeleton): https://github.com/patrick-cullen/env-title/actions/runs/9166402787/job/25201714149
Successful Ubuntu job output: 
```
Run composer require "laravel/framework:10.*" "orchestra/testbench:8.*" "nesbot/carbon:^2.63" --no-interaction --no-update
orchestra/testbench is currently present in the require-dev key and you ran the command without the --dev flag, which will move it to the require key.
./composer.json has been updated
```
Failed Windows job output (note the second line): 
```
Run composer require "laravel/framework:10.*" …
```
=> fix: caret for installing carbon dependency on windows workflow now escaped correctly

phpstan.neon.dist
_With `checkMissingIterableValueType: false` in the config, i get the following output:_
```shell
❯ vendor/bin/phpstan
Note: Using configuration file path/to/project/phpstan.neon.dist.
⚠️  You're using a deprecated config option checkMissingIterableValueType ⚠️️
It's strongly recommended to remove it from your configuration file
and add the missing array typehints.
If you want to continue ignoring missing typehints from arrays,
add missingType.iterableValue error identifier to your ignoreErrors:
parameters:
ignoreErrors:
- identifier: missingType.iterableValue
6/6 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
``` 
_So, I replaced `checkMissingIterableValueType: false` with the following:_
```shell
ignoreErrors:
- identifier: missingType.iterableValue
``` 
_But then, I get a new error:_
```shell
❯ …
```
=> Remove depreciated option from phpstan.neon.dist

src/SkeletonServiceProvider.php
Hi! This PR is intended to solve an issue with the service provider template which uses `skeleton` instead of `migration_table_name` placeholder in the argument of `hasMigration`.
=> Use migration_table_name in service provider

.github/ISSUE_TEMPLATE/config.yml
The URLs for issue templates are using the vendor name, which appears to default to using the full name of the author, not a URL-friendly slug.
=> Fix issue template URLs

.github/ISSUE_TEMPLATE/bug.yml
Spotted this typo in the laravel-pdf repo and thought it'd be best to fix it here rather than in a single repo.
=> fix typo in bug report template

tests/TestCase.php
Hello! Thank you for the nice package, I've used it a lot on (I think) all my packages!
Currently, in the `TestCase` file, people have to manually provide their migration paths. I've always found this a bit surprising/not-DX friendly, as it is very easy to just get and run all migrations instead of manually needing to provide the full path(s). Therefore, this PR replaces it with a simple snippet to just run all migrations in the `database/migrations` path.
The snippet is using the `File::allFiles()` method. This is fine, the only thing is that people would need to import the file after uncommenting for the most clean result. Alternatives like the `scandir()` function are also not great, as `scandir()` is returning results like `.` or `..` and then the snippet to un-comment would start to …
=> Detect migrations automatically in `TestCase`

composer.json
I like to suggest bumping minimum down to php 8.3 too. A lot of packages still have deprecated code for PHP 8.4. Especially the function ($variable = null) which result in a lot of deprecations warnings
=> Allow Larastan 3

.github/workflows/run-tests.yml, composer.json
This PR fixes compatibility issues between composer.json requirements and the GitHub Actions workflow, enabling support for PHP 8.3+ and Laravel 10+.
The current template has several compatibility issues:
- composer.json requires PHP ^8.4, but the workflow tests against PHP 8.3
- Laravel 10 requires Pest v2, but composer.json only allows Pest v3
- The workflow uses a wildcard version for testbench (8.*) which can install incompatible versions during prefer-lowest installations
- Lower PHP requirement from `^8.4` to `^8.3` to match the workflow matrix
- Add support for Pest v2 alongside v3 (`^2.0||^3.0`) for Laravel 10 compatibility
- Update pest plugin constraints to support both v2 and v3 versions
- Change testbench from wildcard (`8.*`) to caret (`^8.22`) to ensure compatible versions …
=> Fix PHP 8.3 and Laravel 10 compatibility

composer.json
Version 2.0 or above does not exist.
=> Remove invalid PHPStan Extension Installer version

composer.json
The recently changed version (`^2.0`) for `phpstan/extension-installer` doesn't exist on [GitHub](https://github.com/phpstan/extension-installer) or [Packagist](https://packagist.org/packages/phpstan/extension-installer).
I've reverted it back to `^1.4`.
Occured to me while trying to upgrade the deps in [my package](https://github.com/ace-of-aces/laravel-image-transform-url) which is using this template :)
=> Fix `phpstan/extension-installer` dependency version
